import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The 32nd MATHirang MATHibay Merch Order Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>

      <body className={inter.className}>
      <img src="https://drive.google.com/thumbnail?id=1nFZ3D1e4TaiWeShsdzhn1YCF8Iz57CqN&sz=w1000" width="400px"></img>
      <p style={{fontSize:35}}> <b> The 32nd MATHirang MATHibay Merch Order Form </b> </p> 

        {children}
    
      </body>
    </html>
  );
}
